using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Debug = UnityEngine.Debug;
using Hpa = HutongGames.PlayMaker.Actions;

public static class RandomInjectionCallsV1 {
    private const BindingFlags allFlags = BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;

    internal static void AddRandomCalls(List<MethodInfo> targetMethods) {
        AddMethodsFromType(targetMethods, typeof(AbyssWaterTendrils), null, "Update");
        AddMethodsFromType(targetMethods, typeof(AchievementHandler), null, "AwardRandomAchievement");
        AddMethodsFromType(targetMethods, typeof(ActivateColliderDelay), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(ActivateObjectRandomDelay), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(ActivateRandomChild), null, "DoActivateRandomChildren");
        AddMethodsFromType(targetMethods, typeof(AirZone), null, "FixedUpdate");
        AddMethodsFromType(targetMethods, typeof(AmbientFloat), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(AmbientFloat), null, "Start");
        AddMethodsFromType(targetMethods, typeof(AmbientSway), null, "Start");
        AddMethodsFromType(targetMethods, typeof(AnimatorGroup), null, "DoAction");
        AddMethodsFromType(targetMethods, typeof(AudioEvent), null, "SelectPitch");
        AddMethodsFromType(targetMethods, typeof(AudioEventRandom), null, "GetClip");
        AddMethodsFromType(targetMethods, typeof(AudioEventRandom), null, "PlayVibrationRandom");
        AddMethodsFromType(targetMethods, typeof(AudioEventRandom), null, "SelectPitch");
        AddMethodsFromType(targetMethods, typeof(AudioEventRandom), null, "SpawnAndPlayOneShotInternal");
        AddMethodsFromType(targetMethods, typeof(AudioLoopRandom), null, "PlayRandom");
        AddMethodsFromType(targetMethods, typeof(AudioManager), null, "BeginApplyAtmosCue");
        AddMethodsFromType(targetMethods, typeof(AudioPlayParticleCollision), null, "OnParticleCollision");
        AddMethodsFromType(targetMethods, typeof(AudioSourcePitchRandomizer), null, "RandomisePitch");
        AddMethodsFromType(targetMethods, typeof(AudioSourcePitchRandomizerV2), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(AudioSourcePitchRandomizerV2), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(AudioSourcePitchRandomizerV3), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(AudioSourcePitchRandomizerV3), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(BasicSpikes), "<Behaviour>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BasicSpriteAnimator), "<Animate>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BellShrineTuningFork), null, "SetInitialState");
        AddMethodsFromType(targetMethods, typeof(BigCentipede), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(BlackThreadImpacter), "<DoAppear>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BlackThreadSpine), null, "Spawned");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrand), null, "GetClosestPosToHero");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrand), null, "StartLoopAudio");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrand), "<BehaviourRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrandSimple), null, "RepositionAndPlay");
        AddMethodsFromType(targetMethods, typeof(BombBounce), null, "OnCollisionEnter2D");
        AddMethodsFromType(targetMethods, typeof(BossStatue), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BossThreadAnimator), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(BossThreadAnimator), null, "Update");
        AddMethodsFromType(targetMethods, typeof(BounceShroom), null, "<Start>b__19_0");
        AddMethodsFromType(targetMethods, typeof(BounceShroom), "<Idle>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(Breakable), null, "Break");
        AddMethodsFromType(targetMethods, typeof(Breakable), null, "FlingDebrisPart");
        AddMethodsFromType(targetMethods, typeof(Breakable), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(Breakable), null, "SpawnNailHitEffect");
        AddMethodsFromType(targetMethods, typeof(Breakable), "FlingObject", "Fling");
        AddMethodsFromType(targetMethods, typeof(BreakableGenerateCorpse), null, "FlingCorpse");
        AddMethodsFromType(targetMethods, typeof(BreakableHolder), "<>c__DisplayClass42_0", "<DoHit>b__0");
        AddMethodsFromType(targetMethods, typeof(BreakableInfectedVine), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(BreakableObject), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(BreakableObject), "FlingObject", "Fling");
        AddMethodsFromType(targetMethods, typeof(BreakablePole), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(BreakablePoleSimple), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(BreakableWithExternalDebris), null, "Spawn");
        //AddMethodsFromType(targetMethods, typeof(CameraShakeProfile), null, "GetOffset");
        //AddMethodsFromType(targetMethods, typeof(CameraShakeResponderMechanim), null, "TryDoShake");
        //AddMethodsFromType(targetMethods, typeof(CameraShakeResponderMechanim), "ShakeEvent", "PlayAnimation");
        //AddMethodsFromType(targetMethods, typeof(CameraShakeResponderMechanim), "ShakeEvent", "StopAnimation");
        AddMethodsFromType(targetMethods, typeof(CharmDisplay), null, "FixedUpdate");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "DoEnableReset");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "FixedUpdate");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "ResetNeedolinTimer");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "Start");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), null, "ToggleSingLoop");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), "<HitLanded>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), "<HitLanded>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), "<Spawn>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(ClockworkHatchling), "<Spawn>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CogCorpseReaction), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(CogCorpseReaction), null, "Update");
        AddMethodsFromType(targetMethods, typeof(CollectableItemHeroReaction), null, "InternalDoReaction");
        AddMethodsFromType(targetMethods, typeof(CollectableItemPickup), null, "FlingSelf");
        AddMethodsFromType(targetMethods, typeof(Corpse), "<DropThroughFloorRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CorpseDeathStun), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CorpseDeathStunChunker), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CorpseFungusExplode), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CorpseGoopExplode), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(CorpseHatcher), null, "Smash");
        AddMethodsFromType(targetMethods, typeof(CorpseItems), null, "GetPickupItems");
        AddMethodsFromType(targetMethods, typeof(CorpseZomHive), null, "LandEffects");
        AddMethodsFromType(targetMethods, typeof(CrestSocketUnlockInventoryDescription), null, "SetConsumeShakeAmount");
        AddMethodsFromType(targetMethods, typeof(CrossSceneWalker), null, "ResetIdleTime");
        AddMethodsFromType(targetMethods, typeof(CrossSceneWalker), null, "Tick");
        AddMethodsFromType(targetMethods, typeof(CrystalPieceSize), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(CurrencyObjectBase), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(CurrencyObjectBase), null, "PlaySound");
        AddMethodsFromType(targetMethods, typeof(CurrencyObjectBase), null, "RandomJostle");
        AddMethodsFromType(targetMethods, typeof(DamageEnemies), null, "CheckOnlyDamageEnemies");
        AddMethodsFromType(targetMethods, typeof(DamageEnemies), null, "DoDamage");
        AddMethodsFromType(targetMethods, typeof(DamageEnemies), null, "DoEnemyDamageNailImbuement");
        AddMethodsFromType(targetMethods, typeof(DeactivateAfter2dtkAnimation), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(DeactivateRandomly), null, "Start");
        AddMethodsFromType(targetMethods, typeof(DebrisParticle), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(DebrisPiece), null, "Launch");
        AddMethodsFromType(targetMethods, typeof(DebrisPiece), null, "Spin");
        AddMethodsFromType(targetMethods, typeof(Dragonfly), null, "StartIdle");
        AddMethodsFromType(targetMethods, typeof(DreamPlantOrb), "<Spread>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(Drip), "<DripRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(DropCrystal), null, "OnCollisionEnter2D");
        AddMethodsFromType(targetMethods, typeof(DropCrystal), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(DropCrystal), null, "Start");
        AddMethodsFromType(targetMethods, typeof(DropPlatform), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(EnemyBullet), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(EnemyDeathEffects), null, "EmitCorpse");
        AddMethodsFromType(targetMethods, typeof(EnemyHitEffectsProfile), "ProfileSection", "PlayRandomVibration");
        AddMethodsFromType(targetMethods, typeof(EnemyHitEffectsProfile), "ProfileSection", "SpawnEffects");
        AddMethodsFromType(targetMethods, typeof(EnemyHitEffectsShade), null, "ReceiveHitEffect");
        AddMethodsFromType(targetMethods, typeof(EnemySingDuration), null, "StartSingCooldown");
        AddMethodsFromType(targetMethods, typeof(EnemySpawner), null, "Start");
        //AddMethodsFromType(targetMethods, typeof(global::Extensions), null, "GetAndRemoveRandomElement");
        //AddMethodsFromType(targetMethods, typeof(global::Extensions), null, "GetRandomElement");
        //AddMethodsFromType(targetMethods, typeof(Extensions), null, "PlayOnSource");
        //AddMethodsFromType(targetMethods, typeof(global::Extensions), null, "RandomInRange");
        //AddMethodsFromType(targetMethods, typeof(global::Extensions), null, "Shuffle");
        AddMethodsFromType(targetMethods, typeof(FakeBat), null, "Start");
        AddMethodsFromType(targetMethods, typeof(FakeBat), "<SendOutRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(FeatherPhysics), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(FlingGameObject), null, "Fling");
        AddMethodsFromType(targetMethods, typeof(FlingGameObjectsAtIntervals), "<SpawnRepeating>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(FlingSelf), null, "DoFling");
        AddMethodsFromType(targetMethods, typeof(FlingUtils), null, "FlingChildren");
        AddMethodsFromType(targetMethods, typeof(FlingUtils), null, "FlingObject");
        AddMethodsFromType(targetMethods, typeof(FlingUtils), null, "SpawnAndFling");
        AddMethodsFromType(targetMethods, typeof(FlingUtils), null, "SpawnAndFlingShellShards");
        AddMethodsFromType(targetMethods, typeof(FloatingPlatform), null, "Start");
        AddMethodsFromType(targetMethods, typeof(FlockFlyer), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(GameManager), null, "SetupSceneRefs");
        AddMethodsFromType(targetMethods, typeof(GameManager), null, "TimePasses");
        AddMethodsFromType(targetMethods, typeof(GameMap), null, "OnAwake");
        AddMethodsFromType(targetMethods, typeof(GlobalSettings.Gameplay), null, "get_ShellShardPrefab");
        AddMethodsFromType(targetMethods, typeof(GlobControl), null, "OnEnable");
        //AddMethodsFromType(targetMethods, typeof(Grass), null, "Hit");
        //AddMethodsFromType(targetMethods, typeof(Grass), null, "Start");
        //AddMethodsFromType(targetMethods, typeof(GrassBehaviour), null, "CutReact");
        //AddMethodsFromType(targetMethods, typeof(GrassBehaviour), null, "OnCameraShaked");
        //AddMethodsFromType(targetMethods, typeof(GrassBehaviour), null, "PlayRandomSound");
        //AddMethodsFromType(targetMethods, typeof(GrassBehaviour), null, "Start");
        //AddMethodsFromType(targetMethods, typeof(GrassSpriteBehaviour), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(GrimmballControl), "<DoFire>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(GrubBGControl), "<Idle>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(HealthCocoon), null, "FlingObjects");
        AddMethodsFromType(targetMethods, typeof(HealthCocoon), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(HealthCocoon), "<Animate>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(HealthFlyer), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(HealthFlyer), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(HealthManager), null, "Die");
        AddMethodsFromType(targetMethods, typeof(HealthManager), null, "SpawnItemDrop");
        AddMethodsFromType(targetMethods, typeof(HealthManager), null, "TakeDamage");
        AddMethodsFromType(targetMethods, typeof(HealthManager), null, "TrySteal");
        AddMethodsFromType(targetMethods, typeof(HeartPieceOrb), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(HeartPieceOrb), null, "Start");
        AddMethodsFromType(targetMethods, typeof(Helper), null, "GetRandomVector2InRange");
        AddMethodsFromType(targetMethods, typeof(Helper), null, "GetRandomVector3InRange");
        AddMethodsFromType(targetMethods, typeof(HeroAnimationController), null, "ResetIdleLook");
        AddMethodsFromType(targetMethods, typeof(HeroAnimationController), null, "UpdateState");
        AddMethodsFromType(targetMethods, typeof(HeroAudioController), null, "RandomizePitch");
        AddMethodsFromType(targetMethods, typeof(HeroBouncer), null, "OnCollisionStay2D");
        AddMethodsFromType(targetMethods, typeof(HeroController), null, "HandleCollisionTouching");
        AddMethodsFromType(targetMethods, typeof(HeroController), null, "TakeDamage");
        AddMethodsFromType(targetMethods, typeof(HeroController), null, "ThrowTool");
        AddMethodsFromType(targetMethods, typeof(HeroController), null, "TryDoTerrainThunk");
        AddMethodsFromType(targetMethods, typeof(HeroCorpseMarker), null, "GetRandom");
        AddMethodsFromType(targetMethods, typeof(HeroWispLantern), null, "GetEnemyInRange");
        AddMethodsFromType(targetMethods, typeof(HitGroundPinned), null, "OnHitInDirection");
        AddMethodsFromType(targetMethods, typeof(HitResponse), null, "Hit");
        //AddMethodsFromType(targetMethods, typeof(HutongGames.PlayMaker.ActionHelpers), null, "GetRandomWeightedIndex");
        AddMethodsFromType(targetMethods, typeof(Hpa.ArrayGetRandom), null, "DoGetRandomValue");
        AddMethodsFromType(targetMethods, typeof(Hpa.ArrayListGetRandom), null, "GetRandomItem");
        AddMethodsFromType(targetMethods, typeof(Hpa.ArrayListShuffle), null, "DoArrayListShuffle");
        AddMethodsFromType(targetMethods, typeof(Hpa.ArrayShuffle), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayerOneShot), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayerOneShotSingle), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayerOneShotSingleV2), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayRandom), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayRandomSingle), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.AudioPlayRandomVoice), null, "DoPlayRandomClip");
        AddMethodsFromType(targetMethods, typeof(Hpa.ChaseObject), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.ChaseObjectSpread), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.CreateObjectsRandom), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.CreatePoolObjects), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.EnemySingControl), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.EnemySingControl), null, "PlaySing");
        AddMethodsFromType(targetMethods, typeof(Hpa.FireAtTarget), null, "DoSetVelocity");
        AddMethodsFromType(targetMethods, typeof(Hpa.Flicker), null, "OnUpdate");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingFlashingGeo), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObject), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjects), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPool), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolTime), null, "OnUpdate");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolV3), null, "DoSpawn");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolV3), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolVel), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsFromGlobalPoolVelTime), null, "OnUpdate");
        AddMethodsFromType(targetMethods, typeof(Hpa.FlingObjectsV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.FloatAddRandom), null, "DoFloatAdd");
        AddMethodsFromType(targetMethods, typeof(Hpa.GetRandomChild), null, "DoGetRandomChild");
        AddMethodsFromType(targetMethods, typeof(Hpa.GetRandomChildOffScreen), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.GetRandomObject), null, "DoGetRandomObject");
        AddMethodsFromType(targetMethods, typeof(Hpa.IdleBuzz), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.IdleBuzzV2), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.IdleBuzzV3), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.IdleBuzzV4), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.ObjectJitter), null, "DoTranslate");
        AddMethodsFromType(targetMethods, typeof(Hpa.ObjectJitterLocal), null, "DoTranslate");
        AddMethodsFromType(targetMethods, typeof(Hpa.ObjectJitterOnRender), null, "OnUpdate");
        AddMethodsFromType(targetMethods, typeof(Hpa.PlayEnemySingAudio), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.PlayRandomAudioClipTableLooped), null, "GetNextPlay");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomBool), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomBoolPercent), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomEvent), null, "GetRandomEvent");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomEvent), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomFloat), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomFloatEither), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomFloatV2), null, "Randomise");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomInt), null, "PickRandom");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomiseAudioPosition), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomVector2), null, "DoAction");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomVector3), null, "DoAction");
        AddMethodsFromType(targetMethods, typeof(Hpa.RandomWait), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SetRandomMaterial), null, "DoSetRandomMaterial");
        AddMethodsFromType(targetMethods, typeof(Hpa.SetRandomRotation), null, "DoRandomRotation");
        AddMethodsFromType(targetMethods, typeof(Hpa.ShakePosition), null, "UpdateShaking");
        AddMethodsFromType(targetMethods, typeof(Hpa.ShakePositionV2), null, "UpdateShaking");
        AddMethodsFromType(targetMethods, typeof(Hpa.SilkBossIdleBuzz), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnFromPool), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnFromPoolV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnObjectFromGlobalPoolDelay), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnObjectFromGlobalPoolOverTimeV2), null, "OnUpdate");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnProjectileV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjects), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsOverTime), null, "DoSpawn");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsOverTimeV2), null, "DoSpawn");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsRadial), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsRadialRandom), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsRadialV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsV2), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.SpawnRandomObjectsVelocity), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.tk2dPlayAnimAfterPreviousCompleteV2), null, "OnAnimationCompleted");
        AddMethodsFromType(targetMethods, typeof(Hpa.Tk2dPlayAnimationChildrenRandom), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.Tk2dPlayRandomAnimationWithEvents), null, "DoPlayAnimationWithEvents");
        AddMethodsFromType(targetMethods, typeof(Hpa.Tk2dSpriteSetIdRandom), null, "DoSetSpriteID");
        AddMethodsFromType(targetMethods, typeof(Hpa.TranslateRandom), null, "DoTranslate");
        AddMethodsFromType(targetMethods, typeof(Hpa.Vector2RandomValue), null, "DoRandomVector2");
        AddMethodsFromType(targetMethods, typeof(Hpa.WaitRandom), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(Hpa.WalkLeftRight), null, "SetupStartingDirection");
        AddMethodsFromType(targetMethods, typeof(Hpa.WispBuzz), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(Hpa.WispBuzz), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(IdleBuzzing), null, "Buzz");
        AddMethodsFromType(targetMethods, typeof(IdleBuzzingV2), null, "Buzz");
        AddMethodsFromType(targetMethods, typeof(IdleForceAnimator), null, "OnCameraShaked");
        AddMethodsFromType(targetMethods, typeof(InfectedBurstLarge), null, "Start");
        AddMethodsFromType(targetMethods, typeof(InfectedBurstSmall), null, "Start");
        AddMethodsFromType(targetMethods, typeof(InvAnimateUpAndDown), null, "Update");
        AddMethodsFromType(targetMethods, typeof(InventoryItemCollectable), null, "SetConsumeShakeAmount");
        AddMethodsFromType(targetMethods, typeof(InventoryItemIconAnimator), null, "OnSelect");
        AddMethodsFromType(targetMethods, typeof(InventoryPaneFollowAudio), "<FadeTo>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(InventoryToolCrestSlot), "<UnlockHoldRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(JellyEgg), null, "Burst");
        AddMethodsFromType(targetMethods, typeof(JitterSelf), null, "ResetAmountLerp");
        AddMethodsFromType(targetMethods, typeof(JumpEffects), null, "PlaySplash");
        AddMethodsFromType(targetMethods, typeof(JumpEffects), null, "SplashOut");
        AddMethodsFromType(targetMethods, typeof(JumpEffects), null, "Update");
        AddMethodsFromType(targetMethods, typeof(KnightHatchling), null, "DoBuzz");
        AddMethodsFromType(targetMethods, typeof(KnightHatchling), null, "FixedUpdate");
        AddMethodsFromType(targetMethods, typeof(KnightHatchling), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(KnightHatchling), null, "Start");
        AddMethodsFromType(targetMethods, typeof(KnightHatchling), "<Spawn>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(LifebloodGlob), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(LiftPlatform), null, "DoBobInternal");
        AddMethodsFromType(targetMethods, typeof(LilyPad), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(LookAnimNPC), null, "Update");
        AddMethodsFromType(targetMethods, typeof(LookAnimNPC), "<Rest>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(MazeController), null, "LinkDoors");
        AddMethodsFromType(targetMethods, typeof(MegaJellyZap), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(MegaJellyZap), "<MultiZapSequence>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(MemoryOrb), "<DoDissipate>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(MinesFlipPlatform), "<Idle>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(MinesFlipPlatform), "<Jitter>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(NeedolinMsgBox), null, "GetNewText");
        AddMethodsFromType(targetMethods, typeof(NPCEncounterStateController), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(ObjectBounce), null, "OnCollisionEnter2D");
        AddMethodsFromType(targetMethods, typeof(PaintBullet), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(PaintBullet), "<Collision>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(PlayChainSound), null, "PlayBrokenHitSound");
        AddMethodsFromType(targetMethods, typeof(PlayChainSound), null, "PlayHitSound");
        AddMethodsFromType(targetMethods, typeof(PlayChainSound), null, "PlayTouchSound");
        AddMethodsFromType(targetMethods, typeof(PlayFromRandomFrame), null, "DoRandomFrame");
        AddMethodsFromType(targetMethods, typeof(PlayFromRandomFrameMecanim), "<DelayStart>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(PlayRandomAnimatorStateOnEnable), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(PlayRandomAudioClip), null, "Play");
        //AddMethodsFromType(targetMethods, typeof(Probability), null, "GetRandomItemRootByProbability");
        AddMethodsFromType(targetMethods, typeof(PuppetThread), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(PuppetThread), null, "Update");
        AddMethodsFromType(targetMethods, typeof(PushableRubble), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(PushableRubble), null, "Push");
        AddMethodsFromType(targetMethods, typeof(RainVibrationRegion), null, "GetRainVibrationPlayer");
        AddMethodsFromType(targetMethods, typeof(RandomAudioClipTable), null, "SelectClip");
        AddMethodsFromType(targetMethods, typeof(RandomAudioClipTable), null, "SelectPitch");
        AddMethodsFromType(targetMethods, typeof(RandomAudioClipTable), null, "SelectVolume");
        AddMethodsFromType(targetMethods, typeof(RandomAudioStart), null, "DoRandomAudioStart");
        AddMethodsFromType(targetMethods, typeof(RandomAudioStartPosition), null, "Start");
        AddMethodsFromType(targetMethods, typeof(RandomiseEnabledChild), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(RandomisePlaybackOffset), null, "OnStateEnter");
        AddMethodsFromType(targetMethods, typeof(RandomLooptk2dAnimator), "<Animate>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(RandomlyFlipScale), null, "ApplyScale");
        AddMethodsFromType(targetMethods, typeof(RandomRotation), null, "RandomRotate");
        AddMethodsFromType(targetMethods, typeof(RandomRotationDelay), "<RandomRotate>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(RandomRotationRange), null, "RandomRotate");
        AddMethodsFromType(targetMethods, typeof(RandomScale), null, "ApplyScale");
        AddMethodsFromType(targetMethods, typeof(RandomSprite), null, "OnEnable");
        //AddMethodsFromType(targetMethods, typeof(RandomTable), null, "TrySelectValue");
        AddMethodsFromType(targetMethods, typeof(RandomTranslation), null, "DoShift");
        AddMethodsFromType(targetMethods, typeof(RangeAttacker), null, "OnInsideStateChanged");
        AddMethodsFromType(targetMethods, typeof(RangeAttacker), "<Anim>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(RecycleAfter2dtkAnimation), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(Rigidbody2DDisturber), "<Rumble>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(Rigidbody2DDisturberImpulse), null, "Impulse");
        AddMethodsFromType(targetMethods, typeof(RosaryCacheShrine), null, "RespondToHit");
        AddMethodsFromType(targetMethods, typeof(RosaryCacheString), null, "FlingRosaries");
        AddMethodsFromType(targetMethods, typeof(SandCentipede), "<Anim>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(SavedFleaActivator), null, "ActivateFleas");
        AddMethodsFromType(targetMethods, typeof(SaveProfileSilkBar), null, "ShowSilk");
        AddMethodsFromType(targetMethods, typeof(SceneData), "<>c", "<MimicShuffle>b__24_0");
        AddMethodsFromType(targetMethods, typeof(SceneryTriggerCircle), null, "RandomizePitch");
        AddMethodsFromType(targetMethods, typeof(ScuttlerControl), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(ScuttlerControl), null, "Start");
        AddMethodsFromType(targetMethods, typeof(ScuttlerControl), "<Bounce>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(SetRandomSpriteId), null, "Init");
        AddMethodsFromType(targetMethods, typeof(SetTriggerRandom), "<TriggerRoutine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(SetWalkerFacing), null, "Apply");
        AddMethodsFromType(targetMethods, typeof(SetZ), null, "DoSetZ");
        AddMethodsFromType(targetMethods, typeof(SetZRandom), null, "DoSetZ");
        AddMethodsFromType(targetMethods, typeof(ShellShard), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(ShellShard), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(ShellShard), "<EnableShineEffect>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(ShineAnimSequence), "<ShineSequence>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(SilkcatcherPlant), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SilkChunk), null, "SetAnims");
        AddMethodsFromType(targetMethods, typeof(SilkChunk), null, "SetUsing");
        AddMethodsFromType(targetMethods, typeof(SilkPossession), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SilkRationMachine), null, "TryDropRation");
        AddMethodsFromType(targetMethods, typeof(SilkRationObject), null, "Land");
        AddMethodsFromType(targetMethods, typeof(SimpleProjectile), null, "DidHit");
        AddMethodsFromType(targetMethods, typeof(SimpleProjectile), null, "OnCollisionEnter2D");
        AddMethodsFromType(targetMethods, typeof(SimpleProjectile), null, "Update");
        AddMethodsFromType(targetMethods, typeof(SimpleRock), null, "OnTriggerEnter");
        AddMethodsFromType(targetMethods, typeof(SimpleRock), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SmashableTile), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(SmashableTile), null, "SetSmashed");
        AddMethodsFromType(targetMethods, typeof(SoftLandEffect), null, "PlaySplash");
        AddMethodsFromType(targetMethods, typeof(SongGateString), null, "QuickStrum");
        AddMethodsFromType(targetMethods, typeof(SongGateString), null, "StrumEnd");
        AddMethodsFromType(targetMethods, typeof(SoulThread), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SpatterHealth), null, "Collect");
        AddMethodsFromType(targetMethods, typeof(SpatterHealth), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SpatterHoney), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SpatterOrange), null, "Impact");
        AddMethodsFromType(targetMethods, typeof(SpatterOrange), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SpawnJarControl), "<Behaviour>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(SpecialQuestItemVariant), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SpellFluke), null, "<Start>b__16_1");
        AddMethodsFromType(targetMethods, typeof(SpellFluke), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SpellGetOrb), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SpellGetOrb), null, "Start");
        AddMethodsFromType(targetMethods, typeof(SpikeCogFall), null, "SetBounced");
        AddMethodsFromType(targetMethods, typeof(SpinSelf), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SpinSelfSimple), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(SplashAnimator), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(StalactiteControl), null, "FlingObjects");
        AddMethodsFromType(targetMethods, typeof(TerrainThunkUtils), null, "GenerateTerrainThunk");
        AddMethodsFromType(targetMethods, typeof(ThiefSnatchEffect), null, "Setup");
        AddMethodsFromType(targetMethods, typeof(ThreadIllumination), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(ThreadIlluminationTK2D), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(ThreadIlluminationTK2D), null, "ThreadStrum");
        AddMethodsFromType(targetMethods, typeof(ThreadSpinner), null, "Hit");
        AddMethodsFromType(targetMethods, typeof(TimeLimitRandomBool), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(TimeLimitSetRandom), null, "OnEnter");
        AddMethodsFromType(targetMethods, typeof(TinkEffect), null, "TryDoTinkReactionNoDamager");
        AddMethodsFromType(targetMethods, typeof(TinyMossFly), null, "Buzz");
        AddMethodsFromType(targetMethods, typeof(TinyMossFly), null, "FixedUpdate");
        AddMethodsFromType(targetMethods, typeof(TinyMossFly), null, "FlyAway");
        AddMethodsFromType(targetMethods, typeof(TinyMossFly), null, "SongStart");
        AddMethodsFromType(targetMethods, typeof(TipOverObject), null, "ShakeEvent");
        AddMethodsFromType(targetMethods, typeof(Tk2dPlayRandomAnimationOnEnable), null, "Play");
        AddMethodsFromType(targetMethods, typeof(ToolPin), null, "Deflect");
        AddMethodsFromType(targetMethods, typeof(ToolPin), null, "Thunk");
        AddMethodsFromType(targetMethods, typeof(ToolPin), null, "Tinked");
        AddMethodsFromType(targetMethods, typeof(ToolPin), null, "TornadoEffect");
        AddMethodsFromType(targetMethods, typeof(ToolRing), null, "DoCogRoll");
        AddMethodsFromType(targetMethods, typeof(ToolRing), null, "OnCollisionEnter2D");
        AddMethodsFromType(targetMethods, typeof(ToolRing), null, "OnDamagedEnemy");
        AddMethodsFromType(targetMethods, typeof(ToolRing), null, "TinkBounce");
        AddMethodsFromType(targetMethods, typeof(ToolRing), null, "TryBounceTowardsEnemy");
        AddMethodsFromType(targetMethods, typeof(TownGrass), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(TrailThread), null, "OnEnable");
        //AddMethodsFromType(targetMethods, typeof(UnityEngine.UI.SaveSlotButton), null, "TryEnterSave");
        //AddMethodsFromType(targetMethods, typeof(UnityStandardAssets.ImageEffects.FastNoise), null, "DrawNoiseQuadGrid");
        AddMethodsFromType(targetMethods, typeof(VectorCurveAnimator), null, "StartAnimationRandomFlip");
        AddMethodsFromType(targetMethods, typeof(Walker), null, "BeginStopped");
        AddMethodsFromType(targetMethods, typeof(Walker), null, "BeginWalking");
        AddMethodsFromType(targetMethods, typeof(Walker), null, "EndStopping");
        AddMethodsFromType(targetMethods, typeof(Walker), null, "StartMoving");
        AddMethodsFromType(targetMethods, typeof(WallClinger), null, "StartMovingDirection");
        AddMethodsFromType(targetMethods, typeof(WaterDisturber), "<Disturb>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(WaterDrip), "<Drip>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(WaterfallParticles), null, "OnTriggerEnter2D");
        AddMethodsFromType(targetMethods, typeof(WeaverlingEnemyList), null, "GetTarget");
        AddMethodsFromType(targetMethods, typeof(WeaverWalkThread), null, "OnEnable");
        AddMethodsFromType(targetMethods, typeof(WorldRumbleManager), null, "GetWaitTime");
        AddMethodsFromType(targetMethods, typeof(WorldRumbleManager), "CameraShake", "GetTargetOffset");
        AddMethodsFromType(targetMethods, typeof(ZapGrassCluster), null, "Start");
        AddMethodsFromType(targetMethods, typeof(ZapGrassCluster), null, "StopZapping");

        //Various methods that call into the hard-patched methods
        AddMethodsFromType(targetMethods, typeof(PlayerData), null, "SetupExistingPlayerData");
        AddMethodsFromType(targetMethods, typeof(BlackThreadState), null, "ChooseAttack");
        AddMethodsFromType(targetMethods, typeof(WorldRumbleManager), null, "DoNewRumble");
        AddMethodsFromType(targetMethods, typeof(ActivateRandomChildrenTimer), "<Routine>d__", "MoveNext");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrandGroup), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(BlackThreadStrandGroup), null, "ResetVisibleStrands");
        AddMethodsFromType(targetMethods, typeof(MazeController), null, "LinkDoors");
        AddMethodsFromType(targetMethods, typeof(NeedolinMsgBox), null, "GetNewText");
        AddMethodsFromType(targetMethods, typeof(SetRandomFsmIndexForChildren), null, "Awake");
        AddMethodsFromType(targetMethods, typeof(SimpleQuestsShopOwner), null, "GetItems");
        AddMethodsFromType(targetMethods, typeof(JitterEnemyInside), null, "Update");
        AddMethodsFromType(targetMethods, typeof(JitterSelf), null, "BatchedUpdate");
    }

    private static void AddMethodsFromType(List<MethodInfo> targetMethods, Type type, string nestedTypeName, string methodName) {
        if (type == null)
            return;

        Type targetType = type;
        if (!string.IsNullOrEmpty(nestedTypeName)) {
            var candidates = type.GetNestedTypes(allFlags).Where(n => n.Name.StartsWith(nestedTypeName)).ToList();
            if (candidates.Count > 1) {
                targetType = candidates.FirstOrDefault(c => c.Name == nestedTypeName);
            }
            if (targetType == type) {
                targetType = candidates.FirstOrDefault();
            }
            if (targetType == null) {
                Debug.Log($"Failed to find nested type {nestedTypeName} in {type.Name}");
                return;
            }
        }

        var methods = targetType.GetMethods(allFlags).Where(m => m.Name == methodName).ToArray();
        if (methods.Length == 0) {
            Debug.Log($"Failed to find method {methodName} in {targetType.Name}");
        } else {
            foreach (var method in methods) {
                Add(targetMethods, method);
            }
        }

    }

    private static void Add(List<MethodInfo> targetMethods, MethodInfo method) {
        if (method != null) {
            targetMethods.Add(method);
            Debug.Log($"Hooked Random in {method.Name}");
        } else {
            Debug.Log("Failed to hook Random as could not locate method");
        }
    }

}